apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres  
    spec:
      containers:
      - name: postgres
        image: postgres:14.3-alpine
        ports:
          - containerPort: 5432
        env :
          - name: POSTGRES_USER
            valueFrom : 
              secretKeyRef :
                name : postgres
                key : POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom : 
              secretKeyRef :
                name : postgres
                key : POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-database-storage
          mountPath: /var/lib/pgsql/data
      volumes:
      - name: postgres-database-storage



---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-srv
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
  

