apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-depl
spec:
  serviceName: postgres-depl
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres  
    spec:
      volumes:
      - name: postgres-pv-volume
        persistentVolumeClaim:
          claimName: postgres-pv-volume
      containers:
      - name: postgres
        image: postgres:14.3-alpine
        ports:
          - containerPort: 5432
        env :
          - name: POSTGRES_USER
            valueFrom : 
              secretKeyRef :
                name : postgres
                key : POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom : 
              secretKeyRef :
                name : postgres
                key : POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-pv-volume
          mountPath: /var/lib/postgresql/data

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-srv
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
  

