apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-volume
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
