apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
spec:
  storageClassName: data
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/data"

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv2
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/storage/data2"

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv3
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/storage/data3"
