
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-depl
spec:
  selector :
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      hostname: kafka
      containers:
      - name: kafka
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        # - name: KAFKA_ADVERTISED_PORT
        #   value: "30718"
        # - name: KAFKA_ADVERTISED_HOST_NAME
        #   value: 192.168.1.240
          # 192.168.1.240
          # 192.168.49.1
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: '0'
        - name: KAFKA_CREATE_TOPICS
          value: first-test:1:1

