apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-blog
spec:
 
  ingressClassName: nginx
  rules:
    - host: okay.blogs.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: authentication-srv
              port:
                number: 3000
                