apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - env:
            - name: REDIS_PASSWORD
              value: "2543"
           
            
            - name: REDIS_DISABLE_COMMANDS
              value: FLUSHDB,FLUSHALL
          image: docker.io/bitnami/redis:7.0
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/redis/data
              name: rdts-redis-data
      restartPolicy: Always
      volumes:
        - name: rdts-redis-data
          persistentVolumeClaim:
            claimName: rdts-redis-data
status: {}
